-- ============================================================
-- IT 자산관리 시스템 v2 — 05_triggers.sql
-- ============================================================
-- [B-4d-2.5] Append-only 트리거 제거 (2026-06-27)
--
-- 사유:
--   1. assets.id FK ON DELETE SET NULL 캐스케이드가
--      equipment_usage_logs.asset_id UPDATE를 발생시키는데,
--      append-only 트리거가 이를 차단하여 자산 삭제 불가.
--   2. v1은 mutable EUL이었으며, v2도 동일 동작으로 복원.
--   3. 이력 보전은 애플리케이션 레벨 정책으로 관리.
--
-- 제거된 객체:
--   DROP TRIGGER  no_update_delete_equipment_usage_logs ON equipment_usage_logs;
--   DROP FUNCTION prevent_update_delete();
-- ============================================================
